const ACTION_TYPE = {
    SET_DATA : "SET_DATA",
    FETCH_DATA: "FETCH_DATA",
    SET_FILTERS: "SET_FILTERS", 
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    LOGOUT : "LOGOUT",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    GET_WISHLIST:"GET_WISHLIST",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
    ADD_CART:"ADD_CART",
    GET_CART:"GET_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
   
}

export default ACTION_TYPE;